collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2595745
  lightness: 0.3787234
  brandStrength: 0
  brandColors:
    - '#010102'
    - '#8988AB'
    - '#F3E002'
    - '#4B4B6E'
    - '#645B01'
  rhythmicContrast: 0
typography_spectrum: 0.93086
layout_spectrum: 0.5337268
name: Filmandy
