color:
  saturation: 0.2403035
  brandStrength: 0.5775717
  rhythmicContrast: 0.7816189
  brandColors:
    - '#010102'
    - '#8988AB'
    - '#F3E002'
    - '#4B4B6E'
    - '#645B01'
  lightness: 0.7934233
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.5337268
typography_spectrum: 0.93086
name: Filmandy
