name: Filmandy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93086
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010102'
    - '#8988AB'
    - '#F3E002'
    - '#4B4B6E'
    - '#645B01'
  brandStrength: 0
  lightness: 0.3787234
  saturation: 0.2595745
  rhythmicContrast: 0
purpose: []
